

#define AppName "Signer"
#ifdef InstallerSmokeTest
  #define AppVersion "0.0.0"
  #define RELEASE_TAG "compile-test"
  #define SIGNER_PART_COUNT 1
  #define SIGNER_DISK_SPACE 1000000
#else
  #ifnexist "..\release\installer_release.iss"
    #error Run scripts/build/prepare_release.bat before compiling this installer
  #endif
  #include "..\release\installer_release.iss"
#endif
#define Publisher "M4X3Corp"
#define PublisherURL "https://github.com/M4X3res/Signer_PRIME"
#define SupportURL "https://github.com/M4X3res/Signer_PRIME/issues"
#define UpdatesURL "https://github.com/M4X3res/Signer_PRIME/releases"

; ──────────────────────────────────────────────────────────────────
; Release configuration — generated by prepare_release.bat
; ──────────────────────────────────────────────────────────────────

#define RELEASE_BASE_URL "https://github.com/M4X3res/Signer_PRIME/releases/download/" + RELEASE_TAG


; ──────────────────────────────────────────────────────────────────
; Optional components — URLs for additional downloads
; ──────────────────────────────────────────────────────────────────
#define CUDA_URL "https://developer.download.nvidia.com/compute/cuda/12.6.0/network_installers/cuda_12.6.0_windows_network.exe"
#define CUDA_SIZE 3200000
#define FFMPEG_URL "https://github.com/BtbN/FFmpeg-Builds/releases/latest/download/ffmpeg-master-latest-win64-gpl.zip"
#define FFMPEG_SIZE 115000000
#define KLITE_URL "https://files2.codecguide.com/K-Lite_Codec_Pack_1995_Standard.exe"
#define KLITE_SIZE 60000000

; ──────────────────────────────────────────────────────────────────
; Branding assets (installer/assets) — optional, auto-detected
; ──────────────────────────────────────────────────────────────────
#define AssetsDir "assets"

; ══════════════════════════════════════════════════════════════════
; Dependency installer plugin
; ══════════════════════════════════════════════════════════════════
#include "InnoDependencyInstaller-master\CodeDependencies.iss"

[Setup]
AppId={{420594D9-8CDA-4304-BC0C-D0ADBE9C8DF3}}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher={#Publisher}
AppPublisherURL={#PublisherURL}
AppSupportURL={#SupportURL}
AppUpdatesURL={#UpdatesURL}
AppContact={#SupportURL}
VersionInfoVersion={#AppVersion}
VersionInfoCompany={#Publisher}
VersionInfoDescription={#AppName} Setup
VersionInfoCopyright=© {#Publisher}
; A user-writable default allows the application to update without elevation.
DefaultDirName={autopf}\Signer
DefaultGroupName=Signer
OutputDir=Output
#ifdef InstallerSmokeTest
OutputBaseFilename=SignerInstaller-COMPILE-TEST-NOT-FOR-DISTRIBUTION
#else
OutputBaseFilename=SignerInstaller-{#AppVersion}
#endif
SetupLogging=yes
WizardSizePercent=110
UninstallDisplayIcon={app}\Signer\Signer.exe
WizardStyle=modern
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
Compression=lzma2
SolidCompression=yes
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableDirPage=no
DisableProgramGroupPage=no
DisableWelcomePage=no
AllowNoIcons=yes
UninstallDisplayName={#AppName}
MinVersion=10.0.17763
CloseApplications=yes
RestartApplications=no
; Временное место на диске СЕЙЧАС физически расходуется на том же диске,
; куда ставится сам Signer (см. RedirectTempToInstallDrive в [Code]) —
; поэтому эта проверка Inno Setup ("хватает ли места на диске {app}")
; впервые стала по-настоящему релевантной для полного объёма загрузки.
; ~4.0GB архив + ~4.3GB распакованные файлы = ~8.4GB
ExtraDiskSpaceRequired={#SIGNER_DISK_SPACE}
ShowLanguageDialog=auto

#ifexist AssetsDir + "\ico.ico"
SetupIconFile={#AssetsDir}\ico.ico
#endif

#ifexist AssetsDir + "\wizard-image.bmp"
WizardImageFile={#AssetsDir}\wizard-image.bmp
#endif

#ifexist AssetsDir + "\wizard-small.bmp"
WizardSmallImageFile={#AssetsDir}\wizard-small.bmp
#endif

#ifexist AssetsDir + "\license.txt"
LicenseFile={#AssetsDir}\license.txt
#endif

#ifexist AssetsDir + "\info_before.txt"
InfoBeforeFile={#AssetsDir}\info_before.txt
#endif

#ifexist AssetsDir + "\info_after.txt"
InfoAfterFile={#AssetsDir}\info_after.txt
#endif

[Languages]
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Types]
Name: "compact"; Description: "Рекомендуемая — Signer и необходимые компоненты"
Name: "full"; Description: "Расширенная — с CUDA Toolkit, FFmpeg и K-Lite"
Name: "custom"; Description: "Выборочная установка"; Flags: iscustom

[Components]
Name: "core"; Description: "Signer (основная программа)"; Types: full compact custom; Flags: fixed
Name: "cuda"; Description: "NVIDIA CUDA Toolkit (ускорение AI, ~3 ГБ)"; Types: full
Name: "ffmpeg"; Description: "FFmpeg (обработка видео, ~115 МБ)"; Types: full
Name: "klite"; Description: "K-Lite Codec Pack (кодеки, ~60 МБ)"; Types: full

[Tasks]
Name: "desktopicon"; Description: "Создать ярлык на рабочем столе"; GroupDescription: "Дополнительно:"; Flags: unchecked
Name: "launchafter"; Description: "Запустить Signer после установки"; GroupDescription: "Дополнительно:"; Flags: unchecked checkedonce

[Files]
Source: "7z.exe"; Flags: dontcopy noencryption
#ifndef InstallerSmokeTest
Source: "7z.dll"; Flags: dontcopy noencryption
#endif
#ifndef InstallerSmokeTest
#include "..\release\installer_downloads.iss"
#include "..\release\installer_payload.iss"
#endif
Source: "{#CUDA_URL}"; DestDir: "{code:GetWorkDir}"; DestName: "cuda.exe"; ExternalSize: {#CUDA_SIZE}; Components: cuda; Flags: external download ignoreversion uninsneveruninstall
Source: "{#FFMPEG_URL}"; DestDir: "{code:GetWorkDir}"; DestName: "ffmpeg.zip"; ExternalSize: {#FFMPEG_SIZE}; Components: ffmpeg; Flags: external download ignoreversion uninsneveruninstall
Source: "{#KLITE_URL}"; DestDir: "{code:GetWorkDir}"; DestName: "klite.exe"; ExternalSize: {#KLITE_SIZE}; Components: klite; Flags: external download ignoreversion uninsneveruninstall

[Icons]
Name: "{group}\Signer"; Filename: "{app}\Signer\Signer.exe"; WorkingDir: "{app}\Signer"
Name: "{group}\{cm:UninstallProgram,Signer}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\Signer"; Filename: "{app}\Signer\Signer.exe"; WorkingDir: "{app}\Signer"; Tasks: desktopicon

[UninstallDelete]
; БАГФИКС: убраны "{tmp}\Signer_extract" и "{tmp}\Signer_parts" —
; такие папки этим скриптом никогда не создавались (мёртвые пути из
; более старой версии скрипта), Inno Setup выдавал бы по ним просто
; безобидный no-op, но они вводили в заблуждение при чтении скрипта.
Type: files; Name: "{app}\*.log"

[Run]
Filename: "{app}\Signer\Signer.exe"; Description: "Запустить Signer сейчас"; Flags: nowait postinstall skipifsilent; Tasks: launchafter

[Code]
#include "DiskWorkspace.iss"
var
  DownloadPage: TDownloadWizardPage;
  ExtractProgressPage: TOutputProgressWizardPage;

  { ── Прогресс загрузки (общий % + % и скорость текущего файла) ── }
  TotalDownloadSize:   Int64;
  DownloadFileNames:   TArrayOfString;
  DownloadFileSizes:   array of Int64;
  DownloadFileCount:   Integer;

  DownloadLastFileName: String;
  DownloadLastTick:     DWORD;
  DownloadLastProgress: Int64;
  DownloadSpeedBps:     Double;

 

  { ── БАГФИКС: защита от задвоения размеров опциональных компонентов
    при повторных попытках загрузки ── }
  OptionalSizesAdded: Boolean;

  { True, если основной архив в этом запуске был восстановлен из
    кэша (см. GetCacheDir) — тогда не нужно ни качать его заново,
    ни повторно копировать в кэш после проверки. }

{ ══════════════════════════════════════════════════════════════════
  Dependencies (InnoDependencyInstaller)
  ══════════════════════════════════════════════════════════════════ }
function GetTickCount: DWORD;
  external 'GetTickCount@kernel32.dll stdcall';

{ БАГФИКС: нужны для RedirectTempToInstallDrive() ниже }
function SetEnvironmentVariable(lpName, lpValue: string): BOOL;
  external 'SetEnvironmentVariableW@kernel32.dll stdcall';

function GetDiskFreeSpaceEx(lpDirectoryName: string;
  var lpFreeBytesAvailable, lpTotalNumberOfBytes, lpTotalNumberOfFreeBytes: Int64): BOOL;
  external 'GetDiskFreeSpaceExW@kernel32.dll stdcall';

{ БАГФИКС: GetLastError — не встроенный идентификатор Pascal Script,
  его нужно импортировать явно (используется в диагностических логах
  ниже, чтобы показывать код ошибки Windows после неудачных вызовов
  ForceDirectories/ShellExec/GetDiskFreeSpaceEx и т.п.). }
function GetLastError: DWORD;
  external 'GetLastError@kernel32.dll stdcall';

function SendMessageTimeout(hWnd: Integer; Msg: Integer; wParam: Integer;
  lParam: String; fuFlags: Integer; uTimeout: Integer; var lpdwResult: Integer): Integer;
  external 'SendMessageTimeoutW@user32.dll stdcall';

const
  { HWND_BROADCAST уже встроен в Inno Setup (переобъявление даёт
    "Duplicate identifier"), а вот WM_SETTINGCHANGE и SMTO_ABORTIFHUNG
    в нём НЕ определены ("Unknown identifier") — их объявляем сами. }
  WM_SETTINGCHANGE = $001A;
  SMTO_ABORTIFHUNG = $0002;

procedure BroadcastEnvironmentChange;
var
  DummyResult: Integer;
begin
  { Сообщаем системе, что переменные окружения изменились — новые
    процессы (cmd, PowerShell и т.д.) подхватят обновлённый PATH
    без перезагрузки; уже открытые окна консоли всё равно нужно
    перезапустить, это ограничение Windows. }
  SendMessageTimeout(HWND_BROADCAST, WM_SETTINGCHANGE, 0, 'Environment',
    SMTO_ABORTIFHUNG, 5000, DummyResult);
end;


{ ══════════════════════════════════════════════════════════════════
  Логирование: только штатный Log() Inno Setup — виден в отчёте после
  установки и пишется на диск только если Setup запущен с /LOG.
  Отдельный always-on файл диагностики (использовался при разборе
  бага с переносом temp-папки) убран из финальной версии.
  ══════════════════════════════════════════════════════════════════ }
procedure DiagLog(const Msg: String);
begin
  Log(Msg);
end;

{ Логирует свободное место на диске, где лежит APath, с понятной
  подписью ALabel — вызывается на каждой ключевой развилке, чтобы
  по логу можно было восстановить, ГДЕ именно кончилось место. }
procedure LogFreeSpace(const APath, ALabel: String);
var
  FreeAvail, TotalBytes, TotalFree: Int64;
  DriveRoot: String;
begin
  DriveRoot := AddBackslash(ExtractFileDrive(APath));
  FreeAvail := 0;
  TotalBytes := 0;
  TotalFree := 0;
  if GetDiskFreeSpaceEx(DriveRoot, FreeAvail, TotalBytes, TotalFree) then
    DiagLog(Format('[DiskSpace] %s -> диск %s: свободно %.0f МБ (всего %.0f Б) из %.0f МБ', [ALabel, DriveRoot, FreeAvail / 1048576.0, FreeAvail * 1.0, TotalBytes / 1048576.0]))
  else
    DiagLog('[DiskSpace] ' + ALabel + ': не удалось прочитать свободное место на ' + DriveRoot +
      ' (GetLastError=' + IntToStr(GetLastError) + ')');
end;

function InitializeSetup: Boolean;
begin
#ifdef InstallerSmokeTest
  MsgBox('Это проверка компиляции, а не установщик релиза. Установка отключена.', mbInformation, MB_OK);
  Result := False;
#else
  Dependency_AddVC14;
  OptionalSizesAdded := False;
  Result := True;
#endif
end;

function FormatBytes(Bytes: Int64): String;
begin
  if Bytes >= 1073741824 then
    Result := Format('%.2f ГБ', [Bytes / 1073741824.0])
  else if Bytes >= 1048576 then
    Result := Format('%.1f МБ', [Bytes / 1048576.0])
  else if Bytes >= 1024 then
    Result := Format('%.1f КБ', [Bytes / 1024.0])
  else
    Result := Format('%d Б', [Bytes]);
end;

function FormatSpeed(BytesPerSec: Double): String;
begin
  if BytesPerSec >= 1048576 then
    Result := Format('%.2f МБ/с', [BytesPerSec / 1048576])
  else if BytesPerSec >= 1024 then
    Result := Format('%.1f КБ/с', [BytesPerSec / 1024])
  else if BytesPerSec > 0 then
    Result := Format('%.0f Б/с', [BytesPerSec])
  else
    Result := '—';
end;

(* ══════════════════════════════════════════════════════════════════
  ПОСЛЕДНИЙ РЕЗЕРВНЫЙ сценарий — вызывается ТОЛЬКО если настоящий
  перенос через перезапуск процесса не сработал вообще нигде:
    - ни в InitializeSetup (ранний диалог, если места на стандартном
      TEMP не хватило);
    - ни в NextButtonClick(wpSelectDir), которая теперь тоже вызывает
      RelaunchSetupWithTempDrive напрямую, если {tmp} текущего процесса
      не совпадает с диском, выбранным для установки — и это ОСНОВНОЙ
      рабочий путь на этой странице, а не эта функция.

  До этого фикса именно эта функция была тем, что вызывалось на
  странице выбора папки — и именно поэтому баг воспроизводился: она
  только дёргает SetEnvironmentVariable, а на уже вычисленный для
  ТЕКУЩЕГО процесса {tmp} это не влияет никак. Теперь она остаётся
  только best-effort подстраховкой на случай, если сам перезапуск
  не удался (не смогли создать целевую папку, Exec не сработал) —
  SetEnvironmentVariable здесь всё ещё бесполезен для {tmp}, но может
  помочь дочерним процессам вроде 7z.exe/CUDA-инсталлятора, плюс даёт
  пользователю честное предупреждение о риске нехватки места вместо
  молчаливого продолжения.
  ══════════════════════════════════════════════════════════════════ *)

function GetFreeBytesForPath(const APath: String): Int64;
var
  FreeAvail, TotalBytes, TotalFree: Int64;
  RootPath: String;
begin
  RootPath := AddBackslash(ExtractFileDrive(APath));
  FreeAvail  := 0;
  TotalBytes := 0;
  TotalFree  := 0;
  if GetDiskFreeSpaceEx(RootPath, FreeAvail, TotalBytes, TotalFree) then
    Result := FreeAvail
  else
    Result := -1;
end;


function DetectCuda: Boolean;
begin
  Result :=
    DirExists(ExpandConstant('{pf}\NVIDIA GPU Computing Toolkit\CUDA')) or
    DirExists(ExpandConstant('{pf64}\NVIDIA GPU Computing Toolkit\CUDA'));
end;

function DetectFFmpeg: Boolean;
var
  EnvPath: String;
begin
  Result := False;
  EnvPath := ExpandConstant('{%PATH}');
  if Pos('ffmpeg', LowerCase(EnvPath)) > 0 then
    Result := True;

  if FileExists(ExpandConstant('{pf}\ffmpeg\bin\ffmpeg.exe')) or
     FileExists(ExpandConstant('{pf64}\ffmpeg\bin\ffmpeg.exe')) then
    Result := True;
end;

function DetectKLite: Boolean;
begin
  Result :=
    RegKeyExists(HKLM, 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\K-Lite Codec Pack_is1') or
    RegKeyExists(HKLM64, 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\K-Lite Codec Pack_is1');
end;

{ ══════════════════════════════════════════════════════════════════
  БАГФИКС: корректное добавление FFmpeg\bin в системный PATH.
  Раньше PATH вообще не прописывался кодом — пользователю просто
  показывалось сообщение "добавьте вручную", причём с ЗАВЕДОМО
  неверным путём: сборки BtbN распаковываются во вложенную папку
  вида "ffmpeg\ffmpeg-master-latest-win64-gpl\bin", а не "ffmpeg\bin".
  (SendMessageTimeout/BroadcastEnvironmentChange теперь объявлены выше,
  рядом с RelaunchSetupWithTempDrive — им обеим нужна эта функция.)
  ══════════════════════════════════════════════════════════════════ }

function AddDirToSystemPath(const Dir: String): Boolean;
var
  CurrentPath: String;
begin
  Result := False;
  if not RegQueryStringValue(HKLM,
       'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
       'Path', CurrentPath) then
    CurrentPath := '';

  { Уже есть — ничего дописывать не нужно (иначе PATH разрастался бы
    при переустановке/повторном запуске инсталлятора). }
  if Pos(LowerCase(';' + Dir + ';'), LowerCase(';' + CurrentPath + ';')) > 0 then
  begin
    Result := True;
    Exit;
  end;

  if (CurrentPath <> '') and (CurrentPath[Length(CurrentPath)] <> ';') then
    CurrentPath := CurrentPath + ';';
  CurrentPath := CurrentPath + Dir;

  if RegWriteStringValue(HKLM,
       'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
       'Path', CurrentPath) then
  begin
    Result := True;
    BroadcastEnvironmentChange;
  end;
end;

{ Ищет реальную папку "bin" внутри распакованного FFmpeg — сначала
  напрямую в RootDir (на случай, если когда-нибудь сборка перестанет
  использовать вложенную папку), затем на один уровень вглубь. }
function FindFFmpegBinDir(const RootDir: String): String;
var
  FindRec: TFindRec;
  Candidate: String;
begin
  Result := '';

  if FileExists(RootDir + '\bin\ffmpeg.exe') then
  begin
    Result := RootDir + '\bin';
    Exit;
  end;

  if FindFirst(RootDir + '\*', FindRec) then
  begin
    try
      repeat
        if (FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY <> 0) and
           (FindRec.Name <> '.') and (FindRec.Name <> '..') then
        begin
          Candidate := RootDir + '\' + FindRec.Name;
          if FileExists(Candidate + '\bin\ffmpeg.exe') then
          begin
            Result := Candidate + '\bin';
            Exit;
          end;
        end;
      until not FindNext(FindRec);
    finally
      FindClose(FindRec);
    end;
  end;
end;

function GetPartFileName(PartIndex: Integer): String;
begin
  if PartIndex < 10 then
    Result := Format('Signer.7z.00%d', [PartIndex])
  else if PartIndex < 100 then
    Result := Format('Signer.7z.0%d', [PartIndex])
  else
    Result := Format('Signer.7z.%d', [PartIndex]);
end;

function GetPartSize(PartIndex, TotalParts: Integer): Int64;
begin
#ifdef InstallerSmokeTest
  Result := 1;
#else
  #include "..\release\installer_sizes.iss"
#endif
end;

{ ── Построение списка файлов для расчёта прогресса ────────────────
  Вызывается один раз в InitializeWizard. Хранит имена и ОЖИДАЕМЫЕ
  (приблизительные) размеры каждой части архива + checksum-файла,
  чтобы взвешенно считать общий процент загрузки по байтам, а не
  просто по количеству файлов (последняя часть архива намного
  меньше остальных). }
procedure BuildDownloadFileList;
var
  I: Integer;
begin
  SetArrayLength(DownloadFileNames, {#SIGNER_PART_COUNT} + 1);
  SetArrayLength(DownloadFileSizes, {#SIGNER_PART_COUNT} + 1);

  TotalDownloadSize := 0;
  for I := 1 to {#SIGNER_PART_COUNT} do
  begin
    DownloadFileNames[I - 1] := GetPartFileName(I);
    DownloadFileSizes[I - 1] := GetPartSize(I, {#SIGNER_PART_COUNT});
    TotalDownloadSize := TotalDownloadSize + DownloadFileSizes[I - 1];
  end;

  DownloadFileNames[{#SIGNER_PART_COUNT}] := 'checksum.sha256';
  DownloadFileSizes[{#SIGNER_PART_COUNT}] := 2048; { маленький текстовый файл }
  TotalDownloadSize := TotalDownloadSize + DownloadFileSizes[{#SIGNER_PART_COUNT}];

  DownloadFileCount := {#SIGNER_PART_COUNT} + 1;
end;

{ Сумма ожидаемых размеров всех файлов, идущих ПЕРЕД указанным —
  используется чтобы посчитать сколько байт уже гарантированно
  скачано из предыдущих файлов при отображении общего прогресса. }
function GetCompletedBytesBefore(const AFileName: String): Int64;
var
  I: Integer;
begin
  Result := 0;
  for I := 0 to DownloadFileCount - 1 do
  begin
    if DownloadFileNames[I] = AFileName then
      Break;
    Result := Result + DownloadFileSizes[I];
  end;
end;

{ БАГФИКС: раньше опциональные компоненты (cuda.exe/ffmpeg.zip/klite.exe)
  не входили в DownloadFileNames/DownloadFileSizes вообще — из-за этого
  GetCompletedBytesBefore() для них не находил совпадения, суммировал
  ВСЕ файлы списка и общий % во время их закачки залипал на 100%.
  Эта функция добавляет компонент в общий расчёт (вызывать РОВНО ОДИН
  РАЗ на компонент — см. OptionalSizesAdded в AddOptionalComponentsToDownload,
  иначе при повторных попытках загрузки размер задвоится). }
procedure AddOptionalComponentSizeToList(const AFileName: String; ASize: Int64);
begin
  SetArrayLength(DownloadFileNames, DownloadFileCount + 1);
  SetArrayLength(DownloadFileSizes, DownloadFileCount + 1);
  DownloadFileNames[DownloadFileCount] := AFileName;
  DownloadFileSizes[DownloadFileCount] := ASize;
  TotalDownloadSize := TotalDownloadSize + ASize;
  DownloadFileCount := DownloadFileCount + 1;
end;

{ ══════════════════════════════════════════════════════════════════
  Кастомный обработчик прогресса загрузки.

  Показывает ОДНОВРЕМЕННО:
    - строка 1: имя текущего файла, его % и объём (скачано/всего)
    - строка 2: общий % по всему архиву + скорость текущего файла
  Прогресс-бар страницы отражает ОБЩИЙ прогресс (полезнее для
  многотомного архива, чем прогресс одного 100MB-куска).
  ══════════════════════════════════════════════════════════════════ }
function OnDownloadProgress(const Url, FileName: String; const Progress, ProgressMax: Int64): Boolean;
var
  FilePercent:    Integer;
  OverallPercent: Integer;
  CompletedBytes: Int64;
  OverallPosition: Int64;
  NowTick:  DWORD;
  ElapsedMs: Int64;
  SpeedText: String;
  Line1, Line2: String;
begin
  { Новый файл начал качаться — сбрасываем счётчик скорости }
  if FileName <> DownloadLastFileName then
  begin
    DownloadLastFileName := FileName;
    DownloadLastTick     := GetTickCount;
    DownloadLastProgress := 0;
    DownloadSpeedBps     := 0;
    LogFreeSpace(ExpandConstant('{tmp}'), 'Начало загрузки файла "' + FileName + '"');
  end;

  if ProgressMax > 0 then
    FilePercent := (Progress * 100) div ProgressMax
  else
    FilePercent := 0;

  CompletedBytes  := GetCompletedBytesBefore(FileName);
  OverallPosition := CompletedBytes + Progress;

  if TotalDownloadSize > 0 then
    OverallPercent := (OverallPosition * 100) div TotalDownloadSize
  else
    OverallPercent := 0;
  if OverallPercent > 100 then
    OverallPercent := 100;

  { Скорость пересчитываем не чаще раза в ~300мс — иначе "скачет" }
  NowTick   := GetTickCount;
  ElapsedMs := NowTick - DownloadLastTick;
  if ElapsedMs >= 300 then
  begin
    DownloadSpeedBps     := (Progress - DownloadLastProgress) * 1000.0 / ElapsedMs;
    DownloadLastTick     := NowTick;
    DownloadLastProgress := Progress;
  end;

  SpeedText := FormatSpeed(DownloadSpeedBps);

  Line1 := Format('Файл: %s — %d%%  (%s / %s)', [FileName, FilePercent, FormatBytes(Progress), FormatBytes(ProgressMax)]);
  Line2 := Format('Общий прогресс: %d%%   Скорость: %s', [OverallPercent, SpeedText]);
  DownloadPage.SetText(Line1, Line2);
  DownloadPage.SetProgress(OverallPosition, TotalDownloadSize);

  { True = продолжить загрузку. Возврат False прервал бы загрузку
    программно — нам это не нужно, прерывание делает сам пользователь
    через кнопку отмены на странице загрузки. }
  Result := True;
end;

{ ══════════════════════════════════════════════════════════════════
  SHA-256 verification via the built-in Windows certutil.exe
  (no bundled hashing tool needed — certutil ships with Windows 7+)
  ══════════════════════════════════════════════════════════════════ }

function ParseChecksumFile(const ChecksumFile, TargetFileName: String): String;
var
  Lines: TArrayOfString;
  I, SpacePos: Integer;
  Line, Hash, Rest: String;
begin
  Result := '';

  if not LoadStringsFromFile(ChecksumFile, Lines) then
    Exit;

  for I := 0 to GetArrayLength(Lines) - 1 do
  begin
    Line := Trim(Lines[I]);
    if (Length(Line) > 0) and (Ord(Line[1]) = $FEFF) then
      Delete(Line, 1, 1);
    if (Line = '') or (Copy(Line, 1, 1) = '#') then
      Continue;

    { Format: "<hash>  <filename>" }
    SpacePos := Pos(' ', Line);
    if SpacePos = 0 then
      Continue;

    Hash := Copy(Line, 1, SpacePos - 1);
    Rest := Trim(Copy(Line, SpacePos + 1, MaxInt));

    { Remove '*' prefix if present }
    if (Rest <> '') and (Copy(Rest, 1, 1) = '*') then
      Rest := Copy(Rest, 2, MaxInt);

    if CompareText(Rest, TargetFileName) = 0 then
    begin
      Result := LowerCase(Hash);
      Exit;
    end;
  end;
end;

function VerifyChecksum(const FilePath, ChecksumFile: String): Boolean;
var
  ExpectedHash, ActualHash: String;
  FileNameOnly: String;
begin
  Result := False;
  FileNameOnly := ExtractFileName(FilePath);

  ExpectedHash := ParseChecksumFile(ChecksumFile, FileNameOnly);
  if ExpectedHash = '' then
  begin
    Log('Warning: no checksum entry found for ' + FileNameOnly);
    Result := False; { Missing hash must block installation }
    Exit;
  end;

  Log('Verifying checksum for ' + FileNameOnly);
  ActualHash := GetSHA256OfFile(FilePath);

  if ActualHash = '' then
  begin
    Log('Error: could not calculate SHA256 for ' + FileNameOnly);
    Result := False;
    Exit;
  end;

  Result := (CompareText(ExpectedHash, ActualHash) = 0);

  if Result then
    Log('✓ Checksum verified: ' + FileNameOnly)
  else
    Log('✗ Checksum MISMATCH: ' + FileNameOnly +
      ' (expected: ' + ExpectedHash + ', actual: ' + ActualHash + ')');
end;

{ ══════════════════════════════════════════════════════════════════
  Кэш скачанного архива (не связано с temp-drive багом).
  Временная папка безвозвратно удаляется Inno Setup при любом выходе из Setup
  (успех, отмена, ошибка распаковки — не важно), поэтому раньше сбой
  на этапе распаковки означал, что при следующем запуске все ~4.3 ГБ
  частей архива приходилось качать заново. Кэшируем уже скачанный и
  проверенный по SHA-256 архив в отдельной папке рядом с приложением, которая
  переживает выход из Setup — при повторном запуске, если кэш цел и
  проходит проверку, скачивание пропускается полностью.
  ══════════════════════════════════════════════════════════════════ }
function GetCacheDir: String;
begin
  Result := ExpandConstant('{app}') + '\..\SignerSetupCache';
end;

function ArchiveCachedAndVerified: Boolean;
var
  I: Integer;
  CacheDir, ChecksumPath, PartPath: String;
begin
  Result := False;
  CacheDir := GetCacheDir;
  ChecksumPath := CacheDir + '\checksum.sha256';
  if not FileExists(ChecksumPath) then
    Exit;

  for I := 1 to {#SIGNER_PART_COUNT} do
  begin
    PartPath := CacheDir + '\' + GetPartFileName(I);
    if not FileExists(PartPath) then
      Exit;
    if not VerifyChecksum(PartPath, ChecksumPath) then
      Exit;
  end;

  Result := True;
end;

procedure RestoreArchiveFromCache;
var
  I: Integer;
  CacheDir: String;
begin
  CacheDir := GetCacheDir;
  Log('[Cache] Восстанавливаем архив из кэша: ' + CacheDir);
  CopyFile(CacheDir + '\checksum.sha256', ExpandConstant('{tmp}\checksum.sha256'), False);
  for I := 1 to {#SIGNER_PART_COUNT} do
    CopyFile(CacheDir + '\' + GetPartFileName(I), ExpandConstant('{tmp}\' + GetPartFileName(I)), False);
end;

procedure CacheVerifiedArchive;
var
  I: Integer;
  CacheDir: String;
begin
  CacheDir := GetCacheDir;
  if not ForceDirectories(CacheDir) then
  begin
    Log('[Cache] Не удалось создать папку кэша ' + CacheDir + ' — пропускаем кэширование');
    Exit;
  end;
  CopyFile(ExpandConstant('{tmp}\checksum.sha256'), CacheDir + '\checksum.sha256', False);
  for I := 1 to {#SIGNER_PART_COUNT} do
    CopyFile(ExpandConstant('{tmp}\' + GetPartFileName(I)), CacheDir + '\' + GetPartFileName(I), False);
  Log('[Cache] Проверенный архив сохранён в кэш: ' + CacheDir);
end;

procedure DeleteArchiveCache;
begin
  DelTree(GetCacheDir, True, True, True);
end;

{ ══════════════════════════════════════════════════════════════════
  Download and extraction of the main Signer archive
  ══════════════════════════════════════════════════════════════════ }

procedure CreateSignerDownloadPage;
begin
  DownloadPage := CreateDownloadPage(
    'Скачивание файлов Signer',
    'Установка скачивает основные файлы приложения с GitHub',
    @OnDownloadProgress
  );
end;

{ ══════════════════════════════════════════════════════════════════
  Add optional components to download list
  ══════════════════════════════════════════════════════════════════ }

procedure AddOptionalComponentsToDownload;
var
  HasCuda, HasFFmpeg, HasKLite: Boolean;
begin
  HasCuda := DetectCuda;
  HasFFmpeg := DetectFFmpeg;
  HasKLite := DetectKLite;

  { Add CUDA if selected and not already installed }
  if WizardIsComponentSelected('cuda') and not HasCuda then
  begin
    Log('Adding CUDA to download list (~3.2 MB network installer)');
    DownloadPage.Add('{#CUDA_URL}', 'cuda.exe', '');
    if not OptionalSizesAdded then
      AddOptionalComponentSizeToList('cuda.exe', {#CUDA_SIZE});
  end;

  { Add FFmpeg if selected and not already installed }
  if WizardIsComponentSelected('ffmpeg') and not HasFFmpeg then
  begin
    Log('Adding FFmpeg to download list (~115 MB)');
    DownloadPage.Add('{#FFMPEG_URL}', 'ffmpeg.zip', '');
    if not OptionalSizesAdded then
      AddOptionalComponentSizeToList('ffmpeg.zip', {#FFMPEG_SIZE});
  end;

  { Add K-Lite if selected and not already installed }
  if WizardIsComponentSelected('klite') and not HasKLite then
  begin
    Log('Adding K-Lite Codec Pack to download list (~60 MB)');
    DownloadPage.Add('{#KLITE_URL}', 'klite.exe', '');
    if not OptionalSizesAdded then
      AddOptionalComponentSizeToList('klite.exe', {#KLITE_SIZE});
  end;

  
  OptionalSizesAdded := True;
end;

procedure InitializeWizard;
begin
  
  WizardForm.Font.Name := 'Segoe UI';
  WizardForm.Font.Size := 10;
  BuildDownloadFileList;
  CreateSignerDownloadPage;

  Log('Total Signer archive download size (approx): ' + FormatBytes(TotalDownloadSize));

  ExtractProgressPage := CreateOutputProgressPage(
    'Распаковка архива',
    'Пожалуйста, подождите...'
  );

  
  WizardForm.WelcomeLabel2.Caption :=
    'Установка Signer ' + '{#AppVersion}' + #13#10#13#10 +
    'Мастер загрузит программу из официального релиза GitHub и проверит целостность файлов.' + #13#10#13#10 +
    'Рекомендуемая установка включает Signer и Microsoft Visual C++. Дополнительные инструменты можно выбрать на следующем шаге.' + #13#10#13#10 +
    'Архив и распакованные файлы временно размещаются на выбранном диске установки. На системном диске нужны только небольшие служебные файлы мастера.';

end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;

  
  if CurPageID = wpReady then
  begin
    if not IsAdminInstallMode and
       (WizardIsComponentSelected('cuda') or WizardIsComponentSelected('ffmpeg') or
        WizardIsComponentSelected('klite')) then
    begin
      SuppressibleMsgBox('Дополнительные системные компоненты требуют установки для всех пользователей. Выберите рекомендуемую установку либо перезапустите установщик в режиме для всех пользователей.', mbInformation, MB_OK, IDOK);
      Result := False;
      Exit;
    end;
    if GetFreeBytesForPath(WizardDirValue) < {#SIGNER_DISK_SPACE} then
    begin
      SuppressibleMsgBox('Недостаточно места на выбранном диске для загрузки и распаковки. Освободите место и повторите установку.', mbError, MB_OK, IDOK);
      Result := False;
      Exit;
    end;

    { Native [Files] downloads run during installation, directly to GetWorkDir. }
    Exit;

  end;
end;

procedure HandleInstallStep(CurStep: TSetupStep);
var
  I: Integer;
  PartPath, ChecksumPath: String;
  ResultCode: Integer;
  AllVerified: Boolean;
  CudaPath, FFmpegPath, KLitePath, FFmpegBinDir: String;
  ExtractLogPath, Exe7zPath, ExtractCmdLine, LogTail: String;
  ExtractLogLines: TArrayOfString;
  StartIdx, J: Integer;
begin
  if CurStep = ssInstall then
  begin
    DiagLog('[Install] ssInstall: {tmp}="' + ExpandConstant('{tmp}') + '"  {app}="' +
      ExpandConstant('{app}') + '"');
    LogFreeSpace(ExpandConstant('{tmp}'), 'Диск {tmp} перед проверкой/распаковкой');
    LogFreeSpace(ExpandConstant('{app}'), 'Диск {app} (установки) перед распаковкой');

    ExtractProgressPage.Show;
    try
      { ── Checksum verification ── }
      ChecksumPath := AddBackslash(GetWorkDir('')) + 'checksum.sha256';
      AllVerified := True;

      if FileExists(ChecksumPath) then
      begin
        ExtractProgressPage.SetText('Проверка целостности файлов...', 'Вычисление SHA-256');
        for I := 1 to {#SIGNER_PART_COUNT} do
        begin
          PartPath := AddBackslash(GetWorkDir('')) + GetPartFileName(I);
          ExtractProgressPage.SetProgress(I, {#SIGNER_PART_COUNT});
          if FileExists(PartPath) then
          begin
            if not VerifyChecksum(PartPath, ChecksumPath) then
            begin
              AllVerified := False;
              Break;
            end;
          end
          else
          begin
            { БАГФИКС: раньше пропавшая часть архива просто молча
              пропускалась в этом цикле (проверка не запускалась и
              AllVerified оставался True) — установка доходила до
              вызова 7-Zip, который падал с менее понятной ошибкой
              "не найден том архива". Теперь это явная ошибка
              целостности, пойманная на этапе проверки. }
            Log('Часть архива не найдена: ' + PartPath);
            AllVerified := False;
            Break;
          end;
        end;
      end
      else
      begin
        { БАГФИКС: раньше отсутствие checksum.sha256 просто писалось в
          лог и проверка ЦЕЛИКОМ пропускалась (AllVerified оставался
          True по умолчанию) — то есть повреждённый/неполный архив мог
          беспрепятственно уйти в распаковку. Файл чексумм — часть
          того же релиза, что и сами части архива, и должен всегда
          загружаться вместе с ними; его отсутствие теперь считается
          ошибкой целостности. }
        Log('checksum.sha256 не найден — целостность не может быть проверена');
        AllVerified := False;
      end;

      if not AllVerified then
      begin
        RaiseException(
          'Проверка целостности скачанных файлов не пройдена. ' +
          'Файл повреждён, отсутствует или подделан. Установка прервана. См. лог для деталей.'
        );
      end;

      { Архив скачан и прошёл проверку SHA-256 — сохраняем копию в кэш
        на случай, если распаковка ниже упадёт (место точно есть, сам
        пользователь подтвердил). Если файлы и так только что пришли
        из кэша — копировать их обратно в тот же кэш незачем. }
      { No duplicate archive cache: downloads already reside on the target disk. }

      { ── Extraction ── }
      ExtractProgressPage.SetText('Распаковка архива...', 'Это может занять несколько минут');
      ExtractProgressPage.SetProgress(0, 100);

      { БАГФИКС: раньше ловили только числовой код возврата 7-Zip —
        для диагностики этого было мало (7-Zip печатает человекочитаемую
        причину в консоль: "Can not open output file", "CRC Failed",
        "ERROR: Not enough memory", "Data Error" и т.п., но этот текст
        никуда не сохранялся). Теперь 7z.exe запускается через cmd.exe
        с перенаправлением stdout/stderr в текстовый файл. Файл кладём
        в каталог приложения, а не во временную папку, которая автоматически
        удаляется Inno Setup при выходе из Setup.exe (успех, отмена,
        ошибка — не важно), а каталог приложения переживает выход и место там уже
        подтверждено достаточным. При неудаче показываем хвост этого
        лога прямо в тексте ошибки — не нужно ничего искать вручную. }
      ExtractLogPath := ExpandConstant('{app}\7z_extract_log.txt');
      ExtractTemporaryFile('7z.exe');
#ifndef InstallerSmokeTest
      ExtractTemporaryFile('7z.dll');
#endif
      Exe7zPath := ExpandConstant('{tmp}\7z.exe');
      ForceDirectories(GetWorkDir('') + '\Signer_payload');
      ExtractCmdLine := '/C ""' + Exe7zPath + '" x "' +
        GetWorkDir('') + '\Signer.7z.001' + '" -o"' + GetWorkDir('') + '\Signer_payload' +
        '" -aoa -y > "' + ExtractLogPath + '" 2>&1"';

      if not Exec(
        ExpandConstant('{cmd}'),
        ExtractCmdLine,
        '',
        SW_HIDE,
        ewWaitUntilTerminated,
        ResultCode
      ) or (ResultCode <> 0) then
      begin
        DiagLog('[Install] 7-Zip вернул код ' + IntToStr(ResultCode) + ' — распаковка не удалась');
        LogFreeSpace(ExpandConstant('{app}'), 'Диск {app} в момент сбоя распаковки');

        LogTail := '(не удалось прочитать лог 7-Zip: ' + ExtractLogPath + ')';
        if LoadStringsFromFile(ExtractLogPath, ExtractLogLines) then
        begin
          LogTail := '';
          StartIdx := 0;
          if GetArrayLength(ExtractLogLines) > 25 then
            StartIdx := GetArrayLength(ExtractLogLines) - 25;
          for J := StartIdx to GetArrayLength(ExtractLogLines) - 1 do
            LogTail := LogTail + ExtractLogLines[J] + #13#10;
          DiagLog('[Install] Хвост лога 7-Zip:' + #13#10 + LogTail);
        end;

        RaiseException(
          'Не удалось распаковать архив. Код ошибки 7-Zip: ' + IntToStr(ResultCode) + #13#10#13#10 +
          'Вывод 7-Zip (последние строки):' + #13#10 + LogTail + #13#10 +
          'Полный лог сохранён здесь: ' + ExtractLogPath
        );
      end;

      { A usable distribution must include the complete update runtime. }
      if not FileExists(GetWorkDir('') + '\Signer_payload\Signer\Signer.exe') or
         not FileExists(GetWorkDir('') + '\Signer_payload\Signer\Updater.exe') or
         not FileExists(GetWorkDir('') + '\Signer_payload\Signer\version.json') or
         not FileExists(GetWorkDir('') + '\Signer_payload\Signer\manifest.json') or
         not FileExists(GetWorkDir('') + '\Signer_payload\Signer\7z.exe') or
         not FileExists(GetWorkDir('') + '\Signer_payload\Signer\7z.dll') then
        RaiseException('В архиве отсутствуют обязательные файлы приложения или обновлятора. Установка не завершена.');

      { Успешная распаковка — лог 7-Zip больше не нужен }
      DeleteFile(ExtractLogPath);

      ExtractProgressPage.SetText('Распаковка завершена', 'Файлы успешно установлены');
      ExtractProgressPage.SetProgress(100, 100);

      DiagLog('✓ Archive extracted successfully');

      { ── Cleanup downloaded parts to save disk space ── }
      ExtractProgressPage.SetText('Очистка временных файлов...', '');
      for I := 1 to {#SIGNER_PART_COUNT} do
      begin
        PartPath := AddBackslash(GetWorkDir('')) + GetPartFileName(I);
        DeleteFile(PartPath);
      end;
      DeleteFile(ChecksumPath);

      Log('✓ Временные файлы очищены');

    finally
      ExtractProgressPage.Hide;
    end;
  end
  else if CurStep = ssPostInstall then
  begin
    { ── Install optional components if downloaded ── }
    ExtractProgressPage.Show;
    try
      { Install CUDA if downloaded }
      CudaPath := GetWorkDir('') + '\cuda.exe';
      if FileExists(CudaPath) then
      begin
        ExtractProgressPage.SetText('Установка NVIDIA CUDA Toolkit...', 'Пожалуйста, подождите');
        ExtractProgressPage.SetProgress(0, 100);
        Log('Installing CUDA from ' + CudaPath);
        
        if Exec(CudaPath, '-s', '', SW_SHOW, ewWaitUntilTerminated, ResultCode) then
        begin
          if ResultCode = 0 then
            Log('✓ CUDA installed successfully')
          else
            Log('Warning: CUDA installer returned code ' + IntToStr(ResultCode));
        end
        else
          Log('Warning: Failed to launch CUDA installer');
        
        DeleteFile(CudaPath);
      end;

      { Install FFmpeg if downloaded }
      FFmpegPath := GetWorkDir('') + '\ffmpeg.zip';
      if FileExists(FFmpegPath) then
      begin
        ExtractProgressPage.SetText('Установка FFmpeg...', 'Распаковка в Program Files');
        ExtractProgressPage.SetProgress(33, 100);
        Log('Installing FFmpeg from ' + FFmpegPath);
        
        if Exec(
          ExpandConstant('{tmp}\7z.exe'),
          Format('x "%s" -o"%s" -aoa -y', [FFmpegPath, ExpandConstant('{pf}\ffmpeg')]),
          '',
          SW_HIDE,
          ewWaitUntilTerminated,
          ResultCode
        ) and (ResultCode = 0) then
        begin
          Log('✓ FFmpeg extracted successfully');

          FFmpegBinDir := FindFFmpegBinDir(ExpandConstant('{pf}\ffmpeg'));
          if FFmpegBinDir <> '' then
          begin
            if AddDirToSystemPath(FFmpegBinDir) then
            begin
              Log('✓ FFmpeg bin добавлен в системный PATH: ' + FFmpegBinDir);
              MsgBox(
                'FFmpeg установлен и добавлен в PATH:' + #13#10 + FFmpegBinDir + #13#10#13#10 +
                'Уже открытые окна командной строки не увидят изменение PATH — ' +
                'перезапустите их (новые окна подхватят PATH сразу).',
                mbInformation, MB_OK
              );
            end
            else
            begin
              Log('Warning: не удалось прописать FFmpeg bin в PATH: ' + FFmpegBinDir);
              MsgBox(
                'FFmpeg установлен в ' + ExpandConstant('{pf}\ffmpeg') + #13#10 +
                'Не удалось автоматически прописать PATH, добавьте вручную:' + #13#10 + FFmpegBinDir,
                mbInformation, MB_OK
              );
            end;
          end
          else
          begin
            { БАГФИКС: раньше здесь всегда показывался путь "ffmpeg\bin",
              которого в реальности не существует — сборки BtbN
              распаковываются во вложенную папку. Теперь честно
              сообщаем, что папка bin не найдена автоматически. }
            Log('Warning: папка bin внутри распакованного FFmpeg не найдена');
            MsgBox(
              'FFmpeg распакован в ' + ExpandConstant('{pf}\ffmpeg') + ', но папка bin ' +
              'не была найдена автоматически. Найдите её вручную и добавьте в PATH.',
              mbInformation, MB_OK
            );
          end;
        end
        else
          Log('Warning: Failed to extract FFmpeg, code ' + IntToStr(ResultCode));
        
        DeleteFile(FFmpegPath);
      end;

      { Install K-Lite Codec Pack if downloaded }
      KLitePath := GetWorkDir('') + '\klite.exe';
      if FileExists(KLitePath) then
      begin
        ExtractProgressPage.SetText('Установка K-Lite Codec Pack...', 'Пожалуйста, подождите');
        ExtractProgressPage.SetProgress(66, 100);
        Log('Installing K-Lite from ' + KLitePath);
        
        if Exec(KLitePath, '/VERYSILENT /NORESTART', '', SW_SHOW, ewWaitUntilTerminated, ResultCode) then
        begin
          if ResultCode = 0 then
            Log('✓ K-Lite installed successfully')
          else
            Log('Warning: K-Lite installer returned code ' + IntToStr(ResultCode));
        end
        else
          Log('Warning: Failed to launch K-Lite installer');
        
        DeleteFile(KLitePath);
      end;

      ExtractProgressPage.SetProgress(100, 100);
    finally
      ExtractProgressPage.Hide;
    end;
  end;
end;

{ Inno Setup manages the uninstall confirmation and removes registered files.
  User-created data and separately installed third-party tools are preserved. }

procedure PreparePayload;
begin
  HandleInstallStep(ssInstall);
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
    HandleInstallStep(ssPostInstall);
end;
